["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
rewards_controller = [
    "./contracts/rewards/rewards_controller.cairo",
]
emission_manager = [
    "./contracts/rewards/emission_manager.cairo",
]
rewards_distributor = [
    "./contracts/rewards/rewards_distributor.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]
